from __future__ import annotations

from dataclasses import dataclass
from enum import Enum, auto
from fractions import Fraction
from typing import Any, Final, Iterable, Iterator, Mapping, Self, Tuple, TypeVar

from flint import Ordering, fmpq, fmpz, fmpq_mpoly, fmpq_mpoly_ctx
from gmpy2 import mpq

from logic1 import firstorder
from logic1.firstorder import _T, _F
from logic1.support.excepthook import NoTraceException


type Constant = float | fmpq | Fraction| int | mpq

_CONSTANT_TYPES = (float, fmpq, Fraction, int, mpq)

def as_fmpq(arg: Constant) -> fmpq:
    if isinstance(arg, float):
        return mpq_to_fmpq(mpq(arg))
    elif isinstance(arg, fmpq):
        return arg
    elif isinstance(arg, Fraction):
        return fmpq(arg.numerator, arg.denominator)
    elif isinstance(arg, int):
        return fmpq(arg)
    elif isinstance(arg, mpq):
        return mpq_to_fmpq(arg)
    else:
        constant_types = ', '.join(c.__name__ for c in _CONSTANT_TYPES)
        raise ValueError(f'expected one of {constant_types}; {arg} is {type(arg)}')

def fmpq_to_mpq(r: fmpq) -> mpq:
    return mpq(int(r.numerator), int(r.denominator))

def mpq_to_fmpq(q: mpq) -> fmpq:
    return fmpq(int(q.numerator), int(q.denominator))


class TermContext:

    _poly_context: fmpq_mpoly_ctx

    def __eq__(self, other: object) -> bool:
        """We efficiently check for identical poly_contexts, because equal
        fmpq_mpoly contexts are always identical. However, note that equal
        TermContexts are not necessarily identical.
        """
        if not isinstance(other, TermContext):
            return False
        return self._poly_context is other._poly_context

    def __init__(self, names: Iterable[str]):
        sorted_names = sorted(names, key=TermContext.sort_key)
        self._poly_context = fmpq_mpoly_ctx.get(sorted_names, 'deglex')

    def __or__(self, other: TermContext) -> TermContext:
        """The ring generated by the union of the generators of self and other.
        """
        if self._poly_context is other._poly_context:
            return self
        else:
            return TermContext(set(self._poly_context.names()) | set(other._poly_context.names()))

    def __repr__(self) -> str:
        return f'TermContext({self._poly_context.names()})'

    def __hash__(self) -> int:
        return hash(self._poly_context)

    def coerce(self, term: Term) -> Term:
        """Coerce term to the TermContext self.
        """
        # The following assertion fires in particular when term contains
        # variables created between VV._stash() and VV._drop(). This is useful
        # because we would return a semantically meaningless term:
        assert not (bad_names := set(term._context.get_names()) - VV._used), \
               f'{term} contains unknown variables {bad_names}'
        return Term.from_raw(self.coerce_poly(term._poly), self)

    def coerce_poly(self, poly: fmpq_mpoly) -> fmpq_mpoly:
        """Coerce poly to the _flint_context of the TermContext self.
        """
        return poly.project_to_context(self._poly_context)

    def get_names(self) -> tuple[str, ...]:
        return self._poly_context.names()

    def get_var_by_index(self, index: int) -> Variable:
        gen = self._poly_context.gen(index)
        return Variable.from_raw(gen, self)

    def get_var_by_name(self, name: str) -> Variable:
        index = self._poly_context.variable_to_index(name)
        return self.get_var_by_index(index)

    def get_vars(self) -> tuple[Variable, ...]:
        return tuple(Variable.from_raw(gen, self) for gen in self._poly_context.gens())

    def ordering(self) -> Ordering:
        return self._poly_context.ordering()

    @staticmethod
    def sort_key(s: str) -> tuple[Any, ...]:  # MyPy has issues with a more specific return type
        base = s.rstrip('0123456789')
        index = s[len(base):]
        n = int(index) if index else -1
        return base, n


class VariableSet(firstorder.atomic.VariableSet['Variable']):
    """The infinite set of all variables belonging to the theory of Real Closed
    Fields. Variables are uniquely identified by their name, which is a
    :external:class:`.str`. This class is a singleton, whose single instance is
    assigned to :data:`.VV`.

    .. seealso::
        Final methods inherited from parent class:

        * :meth:`.firstorder.atomic.VariableSet.get`
            -- obtain several variables simultaneously
        * :meth:`.firstorder.atomic.VariableSet.imp`
            -- import variables into global namespace
    """

    _stack: list[set[str]]

    # required by the abstract parent class
    @property
    def stack(self) -> list[set[str]]:
        return self._stack

    @property
    def _used(self) -> set[str]:
        return self._stack[-1]

    def __getitem__(self, name: str) -> Variable:
        """Implements abstract method :meth:`.firstorder.atomic.VariableSet.__getitem__`.
        """
        if not isinstance(name, str):
            raise ValueError(f'expecting string as index; {name} is {type(name)}')
        context = TermContext([name])
        self._used.add(name)
        return context.get_var_by_index(0)

    def __init__(self) -> None:
        self._reset()

    def __repr__(self) -> str:
        names = sorted(self._used, key=TermContext.sort_key)
        s = ', '.join(name for name in (*names, '...'))
        return f'{{{s}}}'

    def _drop(self) -> None:
        if len(self._stack) <= 1:
            raise ValueError('illegal _drop at bottom of stack')
        self._stack.pop()

    def fresh(self, suffix: str = '') -> Variable:
        """Return a fresh variable, by default from the sequence G0001, G0002,
        ..., G9999, G10000, ... This naming convention is inspired by Lisp's
        gensym(). If the optional argument :data:`suffix` is specified, the
        sequence G0001<suffix>, G0002<suffix>, ... is used instead.
        """
        i = 1
        v = f'G{i:04d}{suffix}'
        while v in self._used:
            i += 1
            v = f'G{i:04d}{suffix}'
        return self[v]

    def merge(self) -> None:
        if len(self._stack) <= 1:
            raise ValueError('illegal merge at bottom of stack')
        self.stack[-2].update(self._stack[-1])
        self.stack.pop()

    def pop(self) -> None:
        raise NotImplementedError()

    def push(self) -> None:
        raise NotImplementedError()

    def _reset(self) -> None:
        self._stack = [set()]

    def stash(self) -> None:
        self._stack.append(set())


VV: Final = VariableSet()
"""
The unique instance of :class:`.VariableSet`.
"""


class DEFINITE(Enum):
    """Information whether a certain term has positive or negative definiteness
    properties; typically as a result of a heuristic test as in
    :meth:`.Term.is_definite`.
    """

    # This is an ordered Enum, the order of the following properties should not
    # be changed.
    UNKNOWN = auto()
    """It has not been derived that any the other cases holds.
    """

    ZERO = auto()
    """The polynomial is the zero polynomial.
    """

    POSITIVE = auto()
    """The polynomial positive definite, i.e., positive for all real choices of
    variables.
    """

    POSITIVE_SEMI = auto()
    """The polynomial positive semi-definite, i.e., non-negative for all real
    choices of variables.
    """

    NEGATIVE = auto()
    """The polynomial negative definite, i.e., negative for all real choices of
    variables.
    """

    NEGATIVE_SEMI = auto()
    """The polynomial negative semi-definite, i.e., non-positive for all real
    choices of variables.
    """

    # The following is an implementation of OrderedEnum as described in
    # https://docs.python.org/3/howto/enum.html#orderedenum
    def __ge__(self, other):
        if self.__class__ is other.__class__:
            return self.value >= other.value
        return NotImplemented

    def __gt__(self, other):
        if self.__class__ is other.__class__:
            return self.value > other.value
        return NotImplemented

    def __le__(self, other):
        if self.__class__ is other.__class__:
            return self.value <= other.value
        return NotImplemented

    def __lt__(self, other):
        if self.__class__ is other.__class__:
            return self.value < other.value
        return NotImplemented

    @staticmethod
    def add(x: DEFINITE, y: DEFINITE) -> DEFINITE:
        """Compute DEFINITE of a sum from DEFINITE of the summands.

        >>> l = list(DEFINITE)

        >>> for x in l:
        ...     for y in l:
        ...             print(f'{x.name} + {y.name} = {DEFINITE.add(x,y).name}')
        ...
        UNKNOWN + UNKNOWN = UNKNOWN
        UNKNOWN + ZERO = UNKNOWN
        UNKNOWN + POSITIVE = UNKNOWN
        UNKNOWN + POSITIVE_SEMI = UNKNOWN
        UNKNOWN + NEGATIVE = UNKNOWN
        UNKNOWN + NEGATIVE_SEMI = UNKNOWN
        ZERO + UNKNOWN = UNKNOWN
        ZERO + ZERO = ZERO
        ZERO + POSITIVE = POSITIVE
        ZERO + POSITIVE_SEMI = POSITIVE_SEMI
        ZERO + NEGATIVE = NEGATIVE
        ZERO + NEGATIVE_SEMI = NEGATIVE_SEMI
        POSITIVE + UNKNOWN = UNKNOWN
        POSITIVE + ZERO = POSITIVE
        POSITIVE + POSITIVE = POSITIVE
        POSITIVE + POSITIVE_SEMI = POSITIVE
        POSITIVE + NEGATIVE = UNKNOWN
        POSITIVE + NEGATIVE_SEMI = UNKNOWN
        POSITIVE_SEMI + UNKNOWN = UNKNOWN
        POSITIVE_SEMI + ZERO = POSITIVE_SEMI
        POSITIVE_SEMI + POSITIVE = POSITIVE
        POSITIVE_SEMI + POSITIVE_SEMI = POSITIVE_SEMI
        POSITIVE_SEMI + NEGATIVE = UNKNOWN
        POSITIVE_SEMI + NEGATIVE_SEMI = UNKNOWN
        NEGATIVE + UNKNOWN = UNKNOWN
        NEGATIVE + ZERO = NEGATIVE
        NEGATIVE + POSITIVE = UNKNOWN
        NEGATIVE + POSITIVE_SEMI = UNKNOWN
        NEGATIVE + NEGATIVE = NEGATIVE
        NEGATIVE + NEGATIVE_SEMI = NEGATIVE
        NEGATIVE_SEMI + UNKNOWN = UNKNOWN
        NEGATIVE_SEMI + ZERO = NEGATIVE_SEMI
        NEGATIVE_SEMI + POSITIVE = UNKNOWN
        NEGATIVE_SEMI + POSITIVE_SEMI = UNKNOWN
        NEGATIVE_SEMI + NEGATIVE = NEGATIVE
        NEGATIVE_SEMI + NEGATIVE_SEMI = NEGATIVE_SEMI

        This addition is commutative:
        >>> all(DEFINITE.add(x, y) is DEFINITE.add(y, x) for x in l for y in l)
        True

        DEFINITE.zero is a (unique) neutral element:
        >>> all(DEFINITE.add(x, DEFINITE.ZERO) is x for x in l)
        True
        """
        x, y = sorted([x, y])
        if x is DEFINITE.UNKNOWN:
            return DEFINITE.UNKNOWN
        if x is DEFINITE.ZERO:
            return y
        if x is DEFINITE.POSITIVE:
            if y is DEFINITE.POSITIVE or y is DEFINITE.POSITIVE_SEMI:
                return DEFINITE.POSITIVE
            assert y is DEFINITE.NEGATIVE or y is DEFINITE.NEGATIVE_SEMI, (x, y)
            return DEFINITE.UNKNOWN
        if x is DEFINITE.POSITIVE_SEMI:
            if y is DEFINITE.POSITIVE_SEMI:
                return DEFINITE.POSITIVE_SEMI
            assert y is DEFINITE.NEGATIVE or y is DEFINITE.NEGATIVE_SEMI, (x, y)
            return DEFINITE.UNKNOWN
        if x is DEFINITE.NEGATIVE:
            assert y is DEFINITE.NEGATIVE or y is DEFINITE.NEGATIVE_SEMI, (x, y)
            return DEFINITE.NEGATIVE
        assert x is DEFINITE.NEGATIVE_SEMI, (x, y)
        assert y is DEFINITE.NEGATIVE_SEMI, (x, y)
        return DEFINITE.NEGATIVE_SEMI

    @staticmethod
    def from_constant(q: int | mpq | fmpq) -> DEFINITE:
        """Compute DEFINITE of a number.

        >>> print(DEFINITE.from_constant(mpq(42)))
        DEFINITE.POSITIVE

        >>> print(DEFINITE.from_constant(mpq(-4711)))
        DEFINITE.NEGATIVE

        >>> print(DEFINITE.from_constant(mpq(0)))
        DEFINITE.ZERO
        """
        assert isinstance(q, (int, mpq, fmpq)), q
        if q > 0:
            return DEFINITE.POSITIVE
        if q < 0:
            return DEFINITE.NEGATIVE
        assert q == 0, q
        return DEFINITE.ZERO

    @staticmethod
    def mul(x: DEFINITE, y: DEFINITE) -> DEFINITE:
        """Compute DEFINITE of a product from DEFINITE of the factors.

        >>> l = list(DEFINITE)

        The multiplication table:
        >>> for x in l:
        ...     for y in l:
        ...             print(f'{x.name} * {y.name} = {DEFINITE.mul(x,y).name}')
        ...
        UNKNOWN * UNKNOWN = UNKNOWN
        UNKNOWN * ZERO = ZERO
        UNKNOWN * POSITIVE = UNKNOWN
        UNKNOWN * POSITIVE_SEMI = UNKNOWN
        UNKNOWN * NEGATIVE = UNKNOWN
        UNKNOWN * NEGATIVE_SEMI = UNKNOWN
        ZERO * UNKNOWN = ZERO
        ZERO * ZERO = ZERO
        ZERO * POSITIVE = ZERO
        ZERO * POSITIVE_SEMI = ZERO
        ZERO * NEGATIVE = ZERO
        ZERO * NEGATIVE_SEMI = ZERO
        POSITIVE * UNKNOWN = UNKNOWN
        POSITIVE * ZERO = ZERO
        POSITIVE * POSITIVE = POSITIVE
        POSITIVE * POSITIVE_SEMI = POSITIVE_SEMI
        POSITIVE * NEGATIVE = NEGATIVE
        POSITIVE * NEGATIVE_SEMI = NEGATIVE_SEMI
        POSITIVE_SEMI * UNKNOWN = UNKNOWN
        POSITIVE_SEMI * ZERO = ZERO
        POSITIVE_SEMI * POSITIVE = POSITIVE_SEMI
        POSITIVE_SEMI * POSITIVE_SEMI = POSITIVE_SEMI
        POSITIVE_SEMI * NEGATIVE = NEGATIVE_SEMI
        POSITIVE_SEMI * NEGATIVE_SEMI = NEGATIVE_SEMI
        NEGATIVE * UNKNOWN = UNKNOWN
        NEGATIVE * ZERO = ZERO
        NEGATIVE * POSITIVE = NEGATIVE
        NEGATIVE * POSITIVE_SEMI = NEGATIVE_SEMI
        NEGATIVE * NEGATIVE = POSITIVE
        NEGATIVE * NEGATIVE_SEMI = POSITIVE_SEMI
        NEGATIVE_SEMI * UNKNOWN = UNKNOWN
        NEGATIVE_SEMI * ZERO = ZERO
        NEGATIVE_SEMI * POSITIVE = NEGATIVE_SEMI
        NEGATIVE_SEMI * POSITIVE_SEMI = NEGATIVE_SEMI
        NEGATIVE_SEMI * NEGATIVE = POSITIVE_SEMI
        NEGATIVE_SEMI * NEGATIVE_SEMI = POSITIVE_SEMI

        This multiplication is commutative:
        >>> all(DEFINITE.mul(x, y) is DEFINITE.mul(y, x) for x in l for y in l)
        True

        DEFINITE.POSITIVE is a (unique) neutral element:
        >>> all(DEFINITE.mul(x, DEFINITE.POSITIVE) is x for x in l)
        True
        """
        x, y = sorted([x, y])
        if x is DEFINITE.UNKNOWN:
            if y is DEFINITE.ZERO:
                return DEFINITE.ZERO
            return DEFINITE.UNKNOWN
        if x is DEFINITE.ZERO:
            return DEFINITE.ZERO
        if x is DEFINITE.POSITIVE:
            return y
        if x is DEFINITE.POSITIVE_SEMI:
            if y is DEFINITE.POSITIVE_SEMI:
                return DEFINITE.POSITIVE_SEMI
            assert y is DEFINITE.NEGATIVE or y is DEFINITE.NEGATIVE_SEMI, (x, y)
            return DEFINITE.NEGATIVE_SEMI
        if x is DEFINITE.NEGATIVE:
            if y is DEFINITE.NEGATIVE:
                return DEFINITE.POSITIVE
            assert y is DEFINITE.NEGATIVE_SEMI, (x, y)
            return DEFINITE.POSITIVE_SEMI
        assert x is DEFINITE.NEGATIVE_SEMI, (x, y)
        assert y is DEFINITE.NEGATIVE_SEMI, (x, y)
        return DEFINITE.POSITIVE_SEMI

    @staticmethod
    def square(x: DEFINITE) -> DEFINITE:
        if x is DEFINITE.UNKNOWN:
            return DEFINITE.POSITIVE_SEMI
        return DEFINITE.mul(x, x)


@dataclass
class SortKey:

    term: Term

    def __eq__(self, other: Self) -> bool:  # type: ignore[override]
        context = self.term._context | other.term._context
        return self.sort_key(context) == other.sort_key(context)

    def __ge__(self, other: Self) -> bool:
        context = self.term._context | other.term._context
        return self.sort_key(context) >= other.sort_key(context)

    def __gt__(self, other: Self) -> bool:
        context = self.term._context | other.term._context
        return self.sort_key(context) > other.sort_key(context)

    def __hash__(self) -> int:
        return hash(self.term)

    def __le__(self, other: Self) -> bool:
        context = self.term._context | other.term._context
        return self.sort_key(context) <= other.sort_key(context)

    def __lt__(self, other: Self) -> bool:
        context = self.term._context | other.term._context
        return self.sort_key(context) < other.sort_key(context)

    def __ne__(self, other: Self) -> bool:  # type: ignore[override]
        context = self.term._context | other.term._context
        return self.sort_key(context) != other.sort_key(context)

    def sort_key(self, context: TermContext) -> Tuple[Any, ...]:
        def exp_key(exp_vec: Tuple[int, ...], ord: Ordering) -> Tuple[Any, ...]:
            """Return a tuple of fmpz such that Python's tuple ordering
            matches the monomial order in `ord` (ascending).
            """
            if ord == Ordering.deglex:
                return (sum(exp_vec), *exp_vec)
            elif ord == Ordering.lex:
                return exp_vec
            elif ord == Ordering.degrevlex:
                return (sum(exp_vec), *(-exp for exp in reversed(exp_vec)))
            raise NotImplementedError(f"Unsupported ordering: {ord!r}")

        def poly_key(poly: fmpq_mpoly, ord: Ordering) -> Tuple[Any, ...]:
            return tuple((exp_key(exp_vec, ord), coeff) for exp_vec, coeff in poly.terms())

        return poly_key(context.coerce_poly(self.term._poly), context.ordering())


class Term(firstorder.Term['Term', 'Variable', int, SortKey]):

    _poly: fmpq_mpoly
    _context: TermContext

    def __add__(self, other: Term | Constant) -> Term:
        if isinstance(other, Term):
            context = self._context | other._context
            sum = context.coerce_poly(self._poly) + context.coerce_poly(other._poly)
            return Term.from_raw(sum, context)
        else:
            return self + Term(other)

    def __eq__(self, other: Term | Constant) -> Eq:  # type: ignore[override]
        # MyPy requires "other: object". However, with our use a a constructor,
        # it makes no sense to compare terms with general objects. We have
        # Eq.__bool__, which supports some comparisons in boolean contexts.
        # Same for __ne__.
        lhs = self - other
        # Use _poly.leadling_coefficient() in order to support @lru_cache on
        # Term.lc().
        if lhs._poly.leading_coefficient() < 0:
            lhs = -lhs
        return Eq(lhs, 0)

    def __ge__(self, other: Term | Constant) -> Ge | Le:
        lhs = self - other
        if lhs.lc() < 0:
            return Le(-lhs, 0)
        else:
            return Ge(lhs, 0)

    def __gt__(self, other: Term | Constant) -> Gt | Lt:
        lhs = self - other
        if lhs.lc() < 0:
            return Lt(-lhs, 0)
        else:
            return Gt(lhs, 0)

    def __hash__(self) -> int:
        # Requires further discussion!
        # return hash((tuple(self._poly.terms()), self._context))
        # return hash(self._poly.terms())
        return hash(repr(self._poly))

    def __init__(self, arg: Constant) -> None:
        """
        >>> Term(0.5)
        1/2
        >>> Term(fmpq(1, 3))
        1/3
        >>> Term(Fraction(1, 4))
        1/4
        >>> Term(42)
        42
        >>> Term(mpq(1, 5))
        1/5
        """
        context = TermContext(())
        poly = context._poly_context.constant(as_fmpq(arg))
        self._poly = poly
        self._context = context

    def __iter__(self) -> Iterator[tuple[mpq, Term]]:
        """Iterate over the polynomial representation of the term, yielding
        pairs of coefficients and monomials.

        >>> from gmpy2 import mpq
        >>> x, y = VV.get('x', 'y')
        >>> t = (x - y + 2) ** 2
        >>> [(abs(coef), power_product) for coef, power_product in t]
        [(mpq(1,1), x^2), (mpq(2,1), x*y), (mpq(1,1), y^2), (mpq(4,1), x),
         (mpq(4,1), y), (mpq(4,1), 1)]
        """
        context = self._context
        poly_factory = context._poly_context.term
        for exp_vec, coeff in self._poly.terms():
            monomial = Term.from_raw(poly_factory(exp_vec=exp_vec), context)
            yield fmpq_to_mpq(coeff), monomial

    def __le__(self, other: Term | Constant) -> Ge | Le:
        lhs = self - other
        if lhs.lc() < 0:
            return Ge(-lhs, 0)
        else:
            return Le(lhs, 0)

    def __len__(self) -> int:
        return len(self._poly)

    def __lt__(self, other: Term | Constant) -> Gt | Lt:
        lhs = self - other
        if lhs.lc() < 0:
            return Gt(-lhs, 0)
        else:
            return Lt(lhs, 0)

    def __mul__(self, other: Term | Constant) -> Term:
        """
        >>> x, y = VV.get('x', 'y')
        >>> (x - y) * (x + y)
        x^2 - y^2
        """
        if isinstance(other, Term):
            context = self._context | other._context
            product = context.coerce_poly(self._poly) * context.coerce_poly(other._poly)
            return Term.from_raw(product, context)
        else:
            return self * Term(other)

    def __ne__(self, other: Term | Constant) -> Ne:  # type: ignore[override]
        lhs = self - other
        if lhs.lc() < 0:
            lhs = -lhs
        return Ne(lhs, Term(0))

    def __neg__(self) -> Term:
        return Term.from_raw(-self._poly, self._context)

    def __pow__(self, exp: int) -> Term:
        return Term.from_raw(self._poly ** exp, self._context)

    def __radd__(self, other: Constant) -> Term:
        assert not isinstance(other, Term)
        return Term(other) + self

    def __repr__(self) -> str:
        return self._as_string(mul='*', pow='**')

    def __rmul__(self, other: Constant) -> Term:
        assert not isinstance(other, Term)
        return Term(other) * self

    def __rsub__(self, other: Constant) -> Term:
        assert not isinstance(other, Term)
        return Term(other) - self

    def __str__(self) -> str:
        return self._as_string(mul=' ', pow='^')

    def __sub__(self, other: Term | Constant) -> Term:
        if isinstance(other, Term):
            context = self._context | other._context
            difference = context.coerce_poly(self._poly) - context.coerce_poly(other._poly)
            return Term.from_raw(difference, context)
        else:
            return self - Term(other)

    def __truediv__(self, other: Term | Constant) -> Term:
        """True division. `self` must be divisible by `other`. Otherwise, flint
        will raise an error.
        """
        if isinstance(other, Term):
            context = self._context | other._context
            quotient = context.coerce_poly(self._poly) / context.coerce_poly(other._poly)
            return Term.from_raw(quotient, context)
        else:
            return self / Term(other)

    def __xor__(self, other: object) -> Term:
        raise NotImplementedError(
            "Use ** for exponentiation, not '^', which means xor "
            "in Python, and has the wrong precedence")

    def as_constant(self) -> mpq:
        if not self.is_constant():
            raise ValueError(f'{self} is not constant')
        return self.constant_coefficient()

    def as_latex(self) -> str:
        """LaTeX representation as a string. Implements the abstract method
        :meth:`.firstorder.atomic.Term.as_latex`.

        >>> from logic1.theories.RCF import VV
        >>> x, y = VV.get('x', 'y')
        >>> t = (x - y + 2) ** 2
        >>> t.as_latex()
        'x^{2} - 2 x y + y^{2} + 4 x - 4 y + 4'
        """
        return self._as_string(mul=' ', pow='^', exp_pre='{', exp_post='}')

    def _as_string(self, mul: str, pow: str, exp_pre: str = '', exp_post: str = '') -> str:

        def _format_first(c: mpq, d) -> str:
            m = _format_mon(d)
            if c == mpq(1):
                return m if m else f'{c}'
            elif c == mpq(-1):
                return f'-{m}' if m else f'{c}'
            elif c != mpq(0):
                return f'{c}{mul}{m}' if m else f'{c}'
            else:
                assert False, f'zero summand in {self!r}'

        def _format_next(c: mpq, d) -> str:
            m = _format_mon(d)
            if c == mpq(1):
                return f' + {m}' if m else f' + {c}'
            elif c == mpq(-1):
                return f' - {m}' if m else f' - {-c}'
            elif c > mpq(0):
                return f' + {c}{mul}{m}' if m else f' + {c}'
            elif c < mpq(0):
                return f' - {-c}{mul}{m}' if m else f' - {-c}'
            else:
                assert False, f'zero summand in {self!r}'

        def _format_var(v: Variable) -> str:
            return repr(v._poly)

        def _format_mon(d: dict[Variable, int]) -> str:
            ret = ''
            for v in self._context.get_vars():
                e = d.get(v, 0)
                if e == 0:
                    continue
                elif e == 1:
                    ret += f'{mul}{_format_var(v)}'
                else:
                    ret += f'{mul}{_format_var(v)}{pow}{exp_pre}{e}{exp_post}'
            return ret.lstrip(mul)

        summands = list(self.summands())
        summands.reverse()
        if not summands:
            return '0'
        d, c = summands.pop()
        ret = [_format_first(c, d)]
        while summands:
            d, c = summands.pop()
            ret.append(_format_next(c, d))
        return ''.join(ret)

    def as_variable(self) -> Variable:
        return Variable.from_raw(self._poly, self._context)

    def coefficient(self, degrees: dict[Variable, int]) -> Term:
        """Return the coefficient of the variables with the degrees specified
        in the python dictionary `degrees`.

        >>> from logic1.theories.RCF import VV
        >>> x, y = VV.get('x', 'y')
        >>> t = (x - y + 2) ** 2
        >>> t.coefficient({x: 1, y: 1})
        -2
        >>> t.coefficient({x: 1})
        -2*y + 4
        """
        raise NotImplementedError()

    def constant_coefficient(self) -> mpq:
        """Return the constant coefficient of this Term.
        """
        summands = tuple(self._poly.terms())
        if summands:
            last_exp_vec, last_coeff = summands[-1]
            if all(exp == 0 for exp in last_exp_vec):
                return fmpq_to_mpq(last_coeff)
        return mpq(0)

    def content(self) -> mpq:
        """Return the content of this term, which is defined as the positive gcd
        of its rational coefficients.

        >>> x, y = VV.get('x', 'y')
        >>> (mpq(2, 3) * x + mpq(4, 9) * y + mpq(8, 15)).content()
        mpq(2,45)
        """
        content = fmpq(0)
        for coeff in self._poly.coeffs():
            content = content.gcd(coeff)
        assert content > 0 or (content == 0 and self == 0)
        return fmpq_to_mpq(content)

    def degree(self, x: Variable) -> int:
        """Return the degree in `x` of this term. `x` is matched against
        variables of `self` by name. The index of the variables in their
        specific TermContext is not relevant. If no variable with the name of
        `x` occurs in the context of `self`, return 0.

        >>> x, y = VV.get('x', 'y')
        >>> (2*y*x**2 + x + 1).degree(x)
        2
        """
        context = self._poly.context()
        names = context.names()
        x_name = repr(x._poly)
        if x_name not in names:
            return 0
        x_index = context.variable_to_index(x_name)
        return self._poly.degrees()[x_index]

    def derivative(self, x: Variable, n: int = 1) -> Term:
        """The `n`-th derivative of this term, with respect to `x`.

        >>> x, y, z = VV.get('x', 'y', 'z')
        >>> (x ** 2 * y + x * z ** 2 + y ** 2 * z).derivative(x)
        2*x*y + z**2
        """
        poly = self._poly
        names = poly.context().names()
        x_name = repr(x._poly)
        if x_name not in names:
            return Term(0)
        for _ in range(n):
            poly = poly.derivative(x_name)
        return Term.from_raw(poly, self._context)

    def factor(self) -> tuple[mpq, dict[Term, int]]:
        """A polynomial factorization of this term.

        A pair `(unit, D)`, where `unit` is a rational number, the
        keys of `D` are irreducible factors, and the corresponding values are
        their multiplicities. All irreducible factors are monic. Note that
        the return value is uniquely determined by this specification.

        >>> from logic1.theories.RCF import VV
        >>> x, y = VV.get('x', 'y')
        >>> t = -x**2 + y**2
        >>> t.factor()
        (mpq(-1,1), {x - y: 1, x + y: 1})
        """
        context = self._context
        unit, factors = self._poly.factor()
        D = dict()
        for factor, exp in factors:
            D[Term.from_raw(factor, context)] = exp
        return fmpq_to_mpq(unit), D

    @classmethod
    def from_raw(cls, poly: fmpq_mpoly, context: TermContext) -> Self:
        self = cls.__new__(cls)
        self._poly = poly
        self._context = context
        return self

    def is_constant(self) -> bool:
        """Return :obj:`True` if this term is constant.
        """
        return self._poly.is_constant()

    def is_monomial(self) -> bool:
        """Check if this term is a monomial. A monomial is a summand without its
        coefficient, i.e., there is a bijection between monomials and exponent
        vectors. In particular, 1 is the only constant monomial.
        """
        coeffs = self._poly.coeffs()
        return len(coeffs) == 1 and coeffs[0] == 1

    def is_variable(self) -> bool:
        """Check if this term is a variable.
        """
        poly = self._poly
        return poly in poly.context().gens()

    def is_zero(self) -> bool:
        """Return :obj:`True` if this term represents the constant zero.
        """
        return self._poly.is_zero()

    def lc(self) -> mpq:
        return fmpq_to_mpq(self._poly.leading_coefficient())

    def sort_key(self) -> SortKey:
        """A sort key suitable for ordering instances of this class. Implements
        the abstract method :meth:`.firstorder.atomic.Term.sort_key`.
        """
        return SortKey(self)

    def subs(self, mapping: Mapping[Variable, Term | Constant]) -> Term:
        """Simultaneous substitution of terms or constants for variables.

        >>> from logic1.theories.RCF import VV
        >>> x, y, z = VV.get('x', 'y', 'z')
        >>> f = 2*y*x**2 + x + 1
        >>> f.subs({x: y, y: 2*z})
        4*y^2*z + y + 1
        """
        proper_term_mapping: dict[Variable, Term] = {}
        constant_mapping: dict[str | int, fmpq] = {}
        for var, substitute in mapping.items():
            if isinstance(substitute, Term):
                if substitute.is_constant():
                    constant_mapping[repr(var._poly)] = mpq_to_fmpq(substitute.as_constant())
                else:
                    proper_term_mapping[var] = substitute
            else:
                constant_mapping[repr(var._poly)] = as_fmpq(substitute)
        # First use fmpq_mpoly.subs for subsituting constants:
        pre_result = Term.from_raw(self._poly.subs(constant_mapping), self._context)
        # Then use arithmetic for the rest:
        result = Term(0)
        for exp_dict, coeff in pre_result.summands():
            for var, exp in exp_dict.items():
                substitute = proper_term_mapping.get(var, var)
                result += Term(coeff) * substitute ** exp
        return result

    def summands(self) -> Iterator[tuple[dict[Variable, int], mpq]]:
        """Iterate over the summands of self yielding pairs of dictionaries
        representing monomials, and coefficients.|
        """
        vars = self._context.get_vars()
        for exp_vec, coeff in self._poly.terms():
            exp_dict = dict()
            for i, exp in enumerate(exp_vec):
                if exp:
                    exp_dict[vars[i]] = exp
            yield exp_dict, fmpq_to_mpq(coeff)

    def unused_vars(self) -> Iterator[Variable]:
        for name in self._poly.unused_gens():
            yield self._context.get_var_by_name(name)

    def vars(self) -> Iterator[Variable]:
        """An iterator that yields each variable of this term once. Implements
        the abstract method :meth:`.firstorder.atomic.Term.vars`.

        .. seealso::
            :external:meth:`MPolynomial_libsingular.variables()
            <sage.rings.polynomial.multi_polynomial_libsingular.MPolynomial_libsingular.variables>`
        """
        unused = set(self.unused_vars())
        for var in self._context.get_vars():
            if var not in unused:
                yield var


class Variable(Term, firstorder.Variable['Variable', int, SortKey]):

    def fresh(self) -> Variable:
        """Returns a variable that has not been used so far. Implements
        abstract method :meth:`.firstorder.atomic.Variable.fresh`.
        """
        return VV.fresh(suffix=f'_{str(self)}')

    @classmethod
    def from_raw(cls, poly: fmpq_mpoly, context: TermContext) -> Self:
        assert poly in poly.context().gens(), f'{poly} is not a generator'
        return super().from_raw(poly, context)

# The following has been literally copied from atomic.py

class AtomicFormula(firstorder.AtomicFormula['AtomicFormula', 'Term', 'Variable', int]):

    @property
    def lhs(self) -> Term:
        """The left hand side term of an atomic formula.
        """
        return self.args[0]

    @property
    def rhs(self) -> Term:
        """The right hand side term of an atomic formula.
        """
        return self.args[1]

    def __bool__(self) -> bool:
        """In boolean contexts atomic formulas are evaluated via corresponding
        comparisons with respect to the degree lexicographical term order
        :mod:`deglex <sage.rings.polynomial.term_order>`. In particular,
        comparisons between terms representing integers follow the natural
        order.
        """
        match self:
            case Eq():
                return self.lhs.sort_key() == self.rhs.sort_key()
            case Ne():
                return self.lhs.sort_key() != self.rhs.sort_key()
            case Ge():
                return self.lhs.sort_key() >= self.rhs.sort_key()
            case Gt():
                return self.lhs.sort_key() > self.rhs.sort_key()
            case Le():
                return self.lhs.sort_key() <= self.rhs.sort_key()
            case Lt():
                return self.lhs.sort_key() < self.rhs.sort_key()
            case _:
                assert False, self

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, AtomicFormula):
            return False
        if self.op != other.op:
            return False
        if self.lhs.sort_key() != other.lhs.sort_key():
            return False
        if self.rhs.sort_key() != other.rhs.sort_key():
            return False
        return True

    def __hash__(self) -> int:
        return super().__hash__()

    def __init__(self, lhs: Term | int, rhs: Term | int):
        super().__init__()
        if not isinstance(self, (Eq, Ne, Ge, Gt, Le, Lt)):
            raise NoTraceException('Instantiate one of Eq, Ne, Ge, Gt, Le, Lt instead')
        if not isinstance(lhs, Term):
            lhs = Term(lhs)
        if not isinstance(rhs, Term):
            rhs = Term(rhs)
        self.args = (lhs, rhs)

    def __le__(self, other: Formula) -> bool:
        """Returns `True` if this atomic formula should be sorted before or is
        equal to other. Implements abstract method
        :meth:`.firstorder.atomic.AtomicFormula.__le__`.
        """
        if not isinstance(other, AtomicFormula):
            return True
        self_sort_key = self.lhs.sort_key()
        other_sort_key = other.lhs.sort_key()
        if self_sort_key != other_sort_key:
            return self_sort_key <= other_sort_key
        self_sort_key = self.rhs.sort_key()
        other_sort_key = other.rhs.sort_key()
        if self_sort_key != other_sort_key:
            return self_sort_key <= other_sort_key
        L = [Eq, Ne, Le, Lt, Ge, Gt]
        return L.index(self.op) <= L.index(other.op)

    def __repr__(self) -> str:
        if self.lhs.is_constant() and self.rhs.is_constant():
            # Return Eq(1, 2) instead of 1 == 2, because the latter is not
            # suitable as input.
            return super().__repr__()
        SYMBOL: Final = {Eq: '==', Ne: '!=', Ge: '>=', Le: '<=', Gt: '>', Lt: '<'}
        SPACING: Final = ' '
        return f'{self.lhs!r}{SPACING}{SYMBOL[self.op]}{SPACING}{self.rhs!r}'


    def __str__(self) -> str:
        """String representation of this atomic formula. Implements the
        abstract method :meth:`.firstorder.atomic.AtomicFormula.__str__`.
        """
        SYMBOL: Final = {Eq: '==', Ne: '!=', Ge: '>=', Le: '<=', Gt: '>', Lt: '<'}
        SPACING: Final = ' '
        return f'{self.lhs}{SPACING}{SYMBOL[self.op]}{SPACING}{self.rhs}'

    def as_latex(self) -> str:
        """Latex representation as a string. Implements the abstract method
        :meth:`.firstorder.atomic.AtomicFormula.as_latex`.
        """
        SYMBOL: Final = {
            Eq: '=', Ne: '\\neq', Ge: '\\geq', Le: '\\leq', Gt: '>', Lt: '<'}
        SPACING: Final = ' '
        return f'{self.lhs.as_latex()}{SPACING}{SYMBOL[self.op]}{SPACING}{self.rhs.as_latex()}'

    def as_redlog(self) -> str:
        """Latex representation as a string. Implements the abstract method
        :meth:`.firstorder.atomic.AtomicFormula.as_latex`.
        """
        SYMBOL: Final = {
            Eq: '=', Ne: '<>', Ge: '>=', Le: '<=', Gt: '>', Lt: '<'}
        return f'({self.lhs!r} {SYMBOL[self.op]} {self.rhs!r})'

    def bvars(self, quantified: frozenset[Variable] = frozenset()) -> Iterator[Variable]:
        """Iterate over occurrences of variables that are elements of
        `quantified`. Yield each such variable once for each term that it
        occurs in. Implements the abstract method
        :meth:`.firstorder.atomic.AtomicFormula.bvars`.
        """
        for v in self.lhs.vars():
            if v in quantified:
                yield v
        for v in self.rhs.vars():
            if v in quantified:
                yield v

    @classmethod
    def complement(cls) -> type[AtomicFormula]:
        """Complement relation. Implements the abstract method
        :meth:`.firstorder.atomic.AtomicFormula.complement`.

        .. seealso::
          Inherited method :meth:`.firstorder.atomic.AtomicFormula.to_complement`
          """
        D: Any = {Eq: Ne, Ne: Eq, Le: Gt, Lt: Ge, Ge: Lt, Gt: Le}
        return D[cls]

    @classmethod
    def converse(cls) -> type[AtomicFormula]:
        """Converse relation.
        """
        D: Any = {Eq: Eq, Ne: Ne, Le: Ge, Lt: Gt, Ge: Le, Gt: Lt}
        return D[cls]

    @classmethod
    def dual(cls) -> type[AtomicFormula]:
        """Dual relation.
        """
        return cls.complement().converse()

    def fvars(self, quantified: frozenset[Variable] = frozenset()) -> Iterator[Variable]:
        """Iterate over occurrences of variables that are *not* elements of
        `quantified`. Yield each such variable once for each term that it
        occurs in. Implements the abstract method
        :meth:`.firstorder.atomic.AtomicFormula.fvars`.
        """
        for v in self.lhs.vars():
            if v not in quantified:
                yield v
        for v in self.rhs.vars():
            if v not in quantified:
                yield v

    def simplify(self) -> Formula:
        """Fast basic simplification. The result is equivalent to self.
        Implements the abstract method :meth:`.firstorder.atomic.AtomicFormula.simplify`.
        """
        lhs = self.lhs - self.rhs
        if lhs.is_constant():
            return _T() if self.op(lhs, 0) else _F()
        if lhs.lc() < 0:
            return self.op.converse()(-lhs, 0)
        return self.op(lhs, 0)

    @classmethod
    def strict_part(cls) -> type[Gt | Lt]:
        """The strict part of a binary relation is the relation without the
        diagonal. Raises :exc:`NotImplementedError` for :class:`Eq` and
        :class:`Ne`.
        """
        if cls in (Eq, Ne):
            raise NotImplementedError()
        D: Any = {Le: Lt, Lt: Lt, Ge: Gt, Gt: Gt}
        return D[cls]

    def subs(self, sigma: Mapping[Variable, Term | int | mpq]) -> Self:
        """Formal simultaneous term substitution into the two argument terms of
        the atomic formula. Implements the abstract method
        :meth:`.firstorder.atomic.AtomicFormula.subs`.
        """
        return self.op(self.lhs.subs(sigma), self.rhs.subs(sigma))

    def subsq(self, sigma: Mapping[Variable, tuple[Term | int | mpq, Term | int | mpq]], is_positive: bool = False) -> Self:
        raise NotImplementedError()

class Eq(AtomicFormula):
    pass

class Ne(AtomicFormula):
    pass


class Ge(AtomicFormula):
    pass


class Le(AtomicFormula):
    pass


class Gt(AtomicFormula):
    pass


class Lt(AtomicFormula):
    pass


# from .typing import Formula
type Formula = firstorder.Formula[AtomicFormula, Term, Variable, int]
