source:
  git: ${{ env.get("LOGIC1_GIT_REPO") }}
  rev: ${{ env.get("LOGIC1_GIT_REV") }}

package:
  name: logic1
  version: ${{ env.get("LOGIC1_VERSION") }}

build:
  number: 0
  script:
    - export CFLAGS="${CFLAGS} -I${SP_DIR}/gmpy2"
    - python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
  host:
    - cython >=3.1.0
    - gmpy2
    - pip
    - python >=3.12
    # - python 3.14.* *_cp314
    - setuptools
    - setuptools_scm
  run:
    - gmpy2
    - more-itertools
    - pyeda
    - python-flint
    - sage
    - typing-extensions

tests:
  - script:
      - export DOT_SAGE="${PWD}/.sage"
      - python -c "import logic1"
  - script:
      - export DOT_SAGE="${PWD}/.sage"
      - python -m doctest -o NORMALIZE_WHITESPACE logic1/theories/Sets/test_qe.txt
    files:
      source:
        - logic1/theories/Sets/test_qe.txt

about:
  license: GPL-2.0-or-later
  summary: Interpreted first-order logic in Python
  homepage: https://docs.logic1.eu/
