from abc import ABC, abstractmethod
from typing import final, Iterable, Optional, Protocol, Self

from logic1 import firstorder
from logic1.theories.RCF.types import _NUMBER_TYPES, Number


class RingElement(Protocol):

    def __add__(self, other: Self) -> Self:
        ...

    def __sub__(self, other: Self) -> Self:
        ...

    def __mul__(self, other: Self) -> Self:
        ...

    def __neg__(self) -> Self:
        ...

    def __eq__(self, other: object) -> bool:
        ...

    def __pow__(self, n: int) -> Self:
        ...

    def __hash__(self) -> int:
        ...

    def __str__(self) -> str:
        ...


class Ring[α: RingElement, β](ABC):

    _ring: β

    @abstractmethod
    def __init__(self, vars_: Iterable[str] = ()) -> None:
        ...

    def __or__(self, other: Ring[α, β]) -> Self:
        """The ring generated by the union of the generators of ``self`` and
        ``other``.
        """
        if self._ring is other._ring:
            return self
        else:
            names = set(self.get_names()) | set(other.get_names())
            return self.__class__(names)

    @abstractmethod
    def coerce_poly(self, x: α) -> α:
        ...

    def get_names(self) -> tuple[str, ...]:
        return tuple(str(var) for var in self.get_gens())

    @abstractmethod
    def get_gens(self) -> tuple[α, ...]:
        ...


class Term[τ: Term, χ: firstorder.Variable, κ, α: RingElement, β](
    firstorder.Term[τ, χ, Number, κ]):

    _hash: Optional[int]
    _poly: α

    @property
    @abstractmethod
    def _parent(self) -> Ring[α, β]:
        ...

    def __add__(self, other: Number | τ) -> τ:
        if isinstance(other, _NUMBER_TYPES):
            other = self.__class__._from_number(other)
        parent = self._parent | other._parent
        self_poly = parent.coerce_poly(self._poly)
        other_poly = parent.coerce_poly(other._poly)
        return self.__class__._from_raw(self_poly + other_poly)

    def __getstate__(self):
        return {"_poly": self._poly}

    def __hash__(self) -> int:
        if self._hash is None:
            self._hash = hash(self._poly)
        return self._hash

    def __mul__(self, other: Number | τ) -> τ:
        if isinstance(other, _NUMBER_TYPES):
            other = self.__class__._from_number(other)
        parent = self._parent | other._parent
        self_poly = parent.coerce_poly(self._poly)
        other_poly = parent.coerce_poly(other._poly)
        return self.__class__._from_raw(self_poly * other_poly)

    def __neg__(self) -> τ:
        return self.__class__._from_raw(-self._poly)

    def __pow__(self, n: int) -> τ:
        if n < 0:
            raise ValueError(f'Negative exponent {n} not supported')
        return self.__class__._from_raw(self._poly ** n)

    def __radd__(self, other: Number | τ) -> τ:
        assert isinstance(other, _NUMBER_TYPES)
        return self.__class__._from_number(other) + self

    def __rmul__(self, other: Number | τ) -> τ:
        assert isinstance(other, _NUMBER_TYPES)
        return self.__class__._from_number(other) * self

    def __rsub__(self, other: Number | τ) -> τ:
        assert isinstance(other, _NUMBER_TYPES)
        return self.__class__._from_number(other) - self

    def __setstate__(self, state):
        self._hash = None
        self._poly = state["_poly"]

    def __str__(self) -> str:
        """Return the mathematical string representation of this term.

        >>> from logic1.theories.RCF import VV
        >>> x, y = VV.get('x', 'y')
        >>> t = (x - y + 2) ** 2
        >>> str(t)
        'x^2 - 2*x*y + y^2 + 4*x - 4*y + 4'
        """
        return str(self._poly)

    def __sub__(self, other: Number | τ) -> τ:
        if isinstance(other, _NUMBER_TYPES):
            other = self.__class__._from_number(other)
        parent = self._parent | other._parent
        self_poly = parent.coerce_poly(self._poly)
        other_poly = parent.coerce_poly(other._poly)
        return self.__class__._from_raw(self_poly - other_poly)

    @final
    def __xor__(self, other: object) -> Term:
        raise NotImplementedError(
            "Use ** for exponentiation, not '^', which means xor "
            "in Python, and has the wrong precedence")


    @classmethod
    @abstractmethod
    def _from_number(cls, num: Number) -> τ:
        ...

    @classmethod
    @abstractmethod
    def _from_raw(cls, value: α) -> τ:
        ...
