name: conda

on:
  push: { branches: [ 'main' ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: '2.0.2-0'
          environment-file: logic1_dev.yaml
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
          generate-run-shell: true

      - name: Build conda package
        run: make conda-build
        shell: micromamba-shell {0}
