name: docs

on:
  push: { branches: [ 'main' ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get -y install graphviz
      - run: |
          source $CONDA/etc/profile.d/conda.sh
          CFLAGS="-Wno-incompatible-pointer-types" conda env create -f logic1_dev.yaml
          conda activate logic1_minimal
          conda env list
          conda list
          export PYTHONPATH="$PYTHONPATH:$(pwd)"
          cd doc
          make html
      - uses: actions/upload-pages-artifact@v3
        with: { path: 'doc/build/html' }

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pages: write
      id-token: write
    environment: { name: 'docs', url: '${{ steps.deployment.outputs.page_url }}' }
    steps: [ { id: 'deployment', uses: 'actions/deploy-pages@v4' } ]
