name: pypi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Initialize Conda
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda config --add channels "conda-forge"
          conda create -y -n logic1 python=3.12 pip sage
      - name: Install dependencies using pip
        run: '"$CONDA/bin/conda" run --no-capture-output -n logic1 python -m pip install .'
      - name: Install pypa/build
        run: '"$CONDA/bin/conda" run --no-capture-output -n logic1 python -m pip install build'
      - name: Build a binary wheel and a source tarball
        run: '"$CONDA/bin/conda" run --no-capture-output -n logic1 python -m build'
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist

  publish:
    name: upload release to TestPyPI
    runs-on: ubuntu-24.04
    needs:
      - build
    environment:
      name: pypi
      url: https://test.pypi.org/p/logic1
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
